### ISSUE TITLE
Code Review 

### ISSUE THREAD

**Issue by Oghenebrume50** [sumancrest0001/HTMLforms#4]
Hello coder,  Nice approach to this project it works properly. I want to point out that the correct way to submit a Microverse project is through a pull request, you should not merge your pull request before you submit. Please follow this for your next submission. 
For now, correct the below errors

- [x] remove the `fieldset` element and replace it with the `main` tag
- [x] the input type of phone number should be `tel` not `number`
- [x] pay attention to the font-size and font-colour of text on the original page, please use the same for your design.
- [x] read up on [Github flow](https://microverse.pathwright.com/library/microverse-onboarding/86777/path/step/53987922/) use it for your next submission of this project and all other HTML projects.

Please make sure to submit the pull request link and not the repository link when submitting for review, pull request should only be merged when a TSE has reviewed and told you everything is fine.

**Comment by rOluochKe** [comment]
all raised issues were completed.
